# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: indexer
ecosystem: fuel
networks:
- id: 0
  start_block: 0
  contracts:
  - name: MemeFactory
    address:
    - 0xbf5c7d76a687a89bb554f54fb45f4a95beac9e1ac81017db35722b0f2cf5685e
    abi_file_path: abis/memefactory-abi.json
    handler: src/EventHandlers.ts
    events:
    - name: PoolInitialized
    - name: TokenSold
    - name: TokenBought
