[project]
authors = ["jibola <pro.ajibolaojo@gmail.com>"]
entry = "main.sw"
license = "Apache-2.0"
name = "dummy-asset"

[dependencies]
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.1" }